{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Chart.Name }}-egress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
  policyTypes:
    - Egress
  {{- if .Values.networkPolicy.egress }}
  egress:
{{ toYaml .Values.networkPolicy.egress | nindent 4 }}
  {{- else }}
  egress: []
  {{- end }}
{{- end }}
