architecture: standalone
auth:
  enabled: false
master:
  persistence:
    enabled: true
    storageClass: local-path
    size: 2Gi
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s
    labels:
      deployment-kit/component: datastore
      deployment-kit/datastore: redis
commonLabels:
  app.kubernetes.io/name: redis
