@startuml
title Целевая архитектура
left to right direction
actor Пользователь as user
cloud "Cloud DNS / hosts
mdp или public domain" as dns
cloud "Yandex CDN
опционально для frontend" as cdn
rectangle "Yandex NLB
80/443" as nlb_ing
rectangle "Ingress nginx" as ing
rectangle "Frontend" as fe
rectangle "Gateway" as gw
rectangle "API" as api
database "PostgreSQL" as pg
rectangle "Redis" as redis
rectangle "Vault" as vault
rectangle "GitLab + Registry" as gitlab
cloud "Контур наблюдаемости
Prometheus/Grafana/Loki/Alloy" as obs
user --> dns
dns --> cdn
dns --> nlb_ing
cdn --> nlb_ing
nlb_ing --> ing
ing --> fe
ing --> gw
ing --> gitlab
gw --> api
api --> pg
api --> redis
api --> vault
gw --> vault
fe --> vault
obs --> gw
obs --> api
obs --> gitlab
@enduml
