architecture: standalone
auth:
  existingSecret: postgres-auth
  secretKeys:
    adminPasswordKey: postgres-password
    userPasswordKey: password
  username: app
  database: appdb
primary:
  persistence:
    enabled: true
    storageClass: local-path
    size: 8Gi
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s
    labels:
      deployment-kit/component: datastore
      deployment-kit/datastore: postgres
commonLabels:
  app.kubernetes.io/name: postgres
