# Файл относится к слою конфигурации и bootstrap Kubernetes-кластера.
# Общие переменные применяются ко всему кластеру.
ansible_user: ubuntu
container_runtime: containerd
kubernetes_packages:
  - kubelet
  - kubeadm
  - kubectl
cluster_artifacts_dir: "{{ playbook_dir }}/../../.artifacts/{{ lookup('env', 'ENV') | default('vm-dev', true) }}"
cluster_name: demo-k8s
kubernetes_version: "1.29.3"
pod_subnet: "10.244.0.0/16"
service_subnet: "10.96.0.0/12"
cni_provider: calico
calico_version: "v3.31.4"
calico_operator_crds_url: "https://raw.githubusercontent.com/projectcalico/calico/v3.31.4/manifests/operator-crds.yaml"
calico_operator_manifest_url: "https://raw.githubusercontent.com/projectcalico/calico/v3.31.4/manifests/tigera-operator.yaml"
calico_encapsulation: VXLAN
calico_nat_outgoing: Enabled
cni_manifest_url: "https://github.com/flannel-io/flannel/releases/download/v0.27.4/kube-flannel.yml"
cni_rollout_namespace: kube-flannel
cni_rollout_resource: daemonset/kube-flannel-ds
kubeadm_min_control_plane_nodes: 3
kubeadm_min_worker_nodes: 1
